services:
  postgres:
    image: postgres:18.3-bookworm
    container_name: postgres_18_3
    restart: unless-stopped
    environment:
      POSTGRES_DB: VKR_Database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 22082004
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      TZ: Europe/Moscow
    ports:
      - "5432:5432"

    volumes:
      - postgres_18_data:/var/lib/postgresql
      
    networks:
      - postgres_network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d VKR_Database"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 256M

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_18
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: zuev22082004@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 22082004
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  postgres_network:
    driver: bridge
    name: postgres_18_network

volumes:
  postgres_18_data:
    name: postgres_18_data
  pgadmin_data:
    name: pgadmin_18_data